version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "./"
    update_schedule: "live"
    default_reviewers:
      - "tianhaoz95"
    default_labels:
      - "gem dependency update"