name: Auto Approval
on: pull_request_target
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.1.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.USE_GITHUB_TOKEN }}"
      - uses: hmarr/auto-approve-action@v2.1.0
        if: github.actor == 'allcontributors[bot]'
        with:
          github-token: "${{ secrets.USE_GITHUB_TOKEN }}"
