name: Auto Approval
on: pull_request
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Approve Dependabot updates
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        with:
          github-token: "${{ secrets.USE_GITHUB_TOKEN }}"
      - name: Approve Allcontributors updates
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'allcontributors[bot]'
        with:
          github-token: "${{ secrets.USE_GITHUB_TOKEN }}"
